name: Build & Deploy
on:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Login to Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF#refs/tags/v} .

      - name: Publish image
        run: docker push --all-tags ghcr.io/${GITHUB_REPOSITORY}

      - name: Logout
        run: docker logout ghcr.io

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      DEPLOYMENT: rest-api
      CONTAINER: rest-api
    steps:

      - name: Set up config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ${HOME}/.kube
          export KUBECONFIG=${HOME}/.kube/config
          echo $KUBE_CONFIG | base64 -d > $KUBECONFIG

      - name: Deploy image
        run: kubectl set image deployment/${DEPLOYMENT} ${CONTAINER}=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF#refs/tags/v}

      - name: Check rollout
        if: success()
        run: kubectl rollout status deployment/${DEPLOYMENT} -w --timeout=5m

      - name: Roll back
        if: failure()
        run: kubectl rollout undo deployment/${DEPLOYMENT}
