name: Build & Deploy
on: release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check if it's a release publish # workaround has `on` doesn't have this filter
        if: github.event.action != 'published'
        run: exit 78

      - name: Login to Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | \
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build image
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\/v//g")
          docker build -t tarkovdatabase/rest-api:${IMAGE_TAG} .

      - name: Publish image
        run: docker push tarkovdatabase/rest-api

      - name: Logout
        run: docker logout

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Set up config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ${HOME}/.kube
          export KUBECONFIG=${HOME}/.kube/config
          echo $KUBE_CONFIG | base64 -d > $KUBECONFIG

      - name: Deploy image
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\/v//g")
          kubectl set image deployment/rest-api rest-api=tarkovdatabase/rest-api:${IMAGE_TAG}
