name: Building/Deploying
on: release
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Login to Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build image
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
          docker build -t tarkovdatabase/rest-api:${IMAGE_TAG} .

      - name: Publish image
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
          docker push tarkovdatabase/rest-api:${IMAGE_TAG}

      - name: Logout
        run: docker logout

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Set up config
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: echo $KUBE_CONFIG | base64 -d > $KUBECONFIG

      - name: Deploy image
        run: |
          export IMAGE_TAG=$(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g")
          kubectl set image deployment/api api-v2=tarkovdatabase/rest-api:${IMAGE_TAG}
